kind: PersistentVolume
apiVersion: v1
metadata:
  name: enm-doorman-pv-volume
  labels:
    purpose: doorman
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/ericmcevoy/DockerK8sCorda/resources/volumes/doorman"

